desc 'Default: build HTML versions of namespace documents'
task default: :html

desc "Build HTML versions of namespace documents"
task html: %w(crypto list log math string time).map {|ns| "#{ns}.html"}

rule ".html" => %w{.n3} do |t|
  puts "build #{t.name}"
  %x{ruby mk_vocab.rb #{t.source}}
end
